site_name: ConGfx Documentation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - API Reference: api.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: lime

  # logo: images/pico.png
  # favicon: images/pico.png
  icon:
    repo: fontawesome/brands/github-alt

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

    - toc.integrate

    - search.suggest
    - search.highlight

    - header.autohide

    # copy button for code 
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhishekmishra/congfx
  analytics:
    provider: google
    property: G-X02ZCZMC1F

# for code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # For emojis and icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

copyright: Copyright &copy; 2025 Abhishek Mishra